# Generated by Django 4.1.3 on 2022-11-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_product_address_alter_product_productowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='driverName',
            field=models.CharField(default='bob', max_length=20),
        ),
    ]
