# Generated by Django 4.1.3 on 2022-11-10 08:39

from django.db import migrations, models
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0019_remove_cartproduct_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='cargo1',
            field=models.CharField(blank=True, default='ihame', max_length=10, null=True, verbose_name=ecomapp.models.Cargo),
        ),
    ]
