# Generated by Django 4.1.3 on 2022-11-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0021_remove_cartproduct_cargo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.cargo'),
        ),
    ]
