# Generated by Django 4.1.3 on 2022-11-10 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0023_alter_cartproduct_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.cargo'),
        ),
    ]
