# Generated by Django 4.1 on 2022-08-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CampanyName', models.CharField(choices=[('Linfox', 'Linfox'), ('Ather', 'Ather')], default='Linfox', max_length=20)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.cargo'),
        ),
    ]
