# Generated by Django 4.1 on 2022-08-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_cargo_cartproduct_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='image',
            field=models.ImageField(default=0, upload_to='products'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
