# Generated by Django 4.1 on 2022-08-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_linfoxuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinfoxImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.cargo')),
            ],
        ),
    ]
