# Generated by Django 4.1 on 2022-08-24 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomapp', '0011_cargo_cargo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='CampanyName',
            field=models.CharField(choices=[('Linfox', 'Linfox'), ('Rwandex', 'Rwandex'), ('Ather', 'Ather')], default='Linfox', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='productowner')),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
