# Generated by Django 4.0.4 on 2022-08-27 08:54

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_alter_cargo_campanyname_productowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productowner',
            field=models.CharField(default='ihamegrbt@gmail.com', max_length=300, verbose_name=django.contrib.auth.models.AbstractUser.get_full_name),
        ),
    ]
