# Generated by Django 4.1.3 on 2022-11-09 14:08

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0015_alter_product_productowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='productowner',
            field=models.CharField(max_length=300, verbose_name=django.contrib.auth.models.AbstractUser.get_full_name),
        ),
    ]
