# Generated by Django 4.1.3 on 2022-11-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_product_address_alter_product_productowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='driverName',
            field=models.CharField(default='bob', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='cargo',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.cargo'),
        ),
    ]
