# Generated by Django 4.1.3 on 2022-11-10 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0017_cargo_drivername_alter_cartproduct_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='address',
            field=models.CharField(blank=True, default='kk 310st', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='admin',
            name='captcha_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='admin',
            name='county',
            field=models.CharField(blank=True, default='Rwanda', max_length=100, null=True, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='admin',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='latitude',
            field=models.CharField(blank=True, default='1', max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='admin',
            name='longitude',
            field=models.CharField(blank=True, default='1', max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='admin',
            name='post_code',
            field=models.CharField(blank=True, default='00000', max_length=8, null=True, verbose_name='Post Code'),
        ),
        migrations.AddField(
            model_name='admin',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='town',
            field=models.CharField(blank=True, default='kigali', max_length=100, null=True, verbose_name='Town/City'),
        ),
        migrations.AddField(
            model_name='admin',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
