# Generated by Django 4.1.3 on 2022-11-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0018_admin_address_admin_captcha_score_admin_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='county',
            field=models.CharField(blank=True, default='Rwanda', max_length=100, null=True, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='town',
            field=models.CharField(blank=True, default='kigali', max_length=100, null=True, verbose_name='Town/City'),
        ),
        migrations.AddField(
            model_name='product',
            name='county',
            field=models.CharField(blank=True, default='Rwanda', max_length=100, null=True, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='product',
            name='town',
            field=models.CharField(blank=True, default='kigali', max_length=100, null=True, verbose_name='Town/City'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='address',
            field=models.CharField(blank=True, default='kk 310st', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='kk 310st', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.CharField(blank=True, default='kk 330st', max_length=100, null=True, verbose_name='Address'),
        ),
    ]
