# Generated by Django 4.1.3 on 2022-11-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0019_customer_county_customer_is_active_customer_town_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='captcha_score',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='longitude',
        ),
    ]
