# Generated by Django 3.2.5 on 2022-12-03 07:53

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0023_auto_20221203_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productowneremail',
            field=models.CharField(default=' ', max_length=300, verbose_name=django.contrib.auth.models.AbstractUser.get_full_name),
        ),
        migrations.AlterField(
            model_name='product',
            name='productowner',
            field=models.CharField(max_length=300),
        ),
    ]
