# Generated by Django 3.2.5 on 2022-12-03 08:03

import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0024_auto_20221203_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productowneremail',
            field=models.CharField(default=' ', max_length=300, verbose_name=django.contrib.auth.base_user.AbstractBaseUser.get_username),
        ),
    ]
