# Generated by Django 3.2.5 on 2022-12-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0028_auto_20221204_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
