# Generated by Django 3.2.5 on 2022-12-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0029_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='driverName',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
